apiVersion: v1
kind: Namespace
metadata:
  name: k8s-demo

---

apiVersion: v1
data:
  mysqld.cnf: |-
    [mysqld]
    datadir=/var/lib/mysql
    socket=/var/lib/mysql/mysql.sock
    symbolic-links=0
    log-error=/var/log/mysqld.log
    pid-file=/var/run/mysqld/mysqld.pid
    character-set-server=utf8

    [client]
    default-character-set=utf8
kind: ConfigMap
metadata:
    name: mysql-config
    namespace: k8s-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: mysql-config-volume
              mountPath: "/etc/mysql/mysql.conf.d/"
            - name: log-volume
              mountPath: "/var/log"
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
        - name: log-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: k8s-demo
  labels:
    name: mysql-svc
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: http
      nodePort: 30036
  selector:
    app: mysql